### ISSUE TITLE
[Suggestion] SimpleHarvest compatibility

### ISSUE THREAD

**Issue by ProspectPyxis** [coderbot16/SimpleFlax#5]
Currently, using SimpleHarvest's right click harvest function breaks off the top of the flax plant and leaves a glitched bottom part. Integration with right click harvesting in general would be nice.

**Comment by coderbot16** [comment]
Good idea, I'll look into it this weekend. In general harvest mods break with mods like mine since they aren't meant to handle multi block plants, as can be seen with other mods like Simple Corn.

**Comment by coderbot16** [comment]
https://github.com/coderbot16/SimpleFlax/commit/867313b1993f1c66cc543b2cd90fe9d1949cdd94 fixes this issue, and a release will be uploaded to CurseForge soon. Note that it might take up to 24 hours due to delay in the approval process. Thanks for reporting this issue, and feel free to open another issue if you have more questions!

**Comment by coderbot16** [comment]
@ProspectPyxis The release has been approved, hopefully it resolves your issue!
