### ISSUE TITLE
[Suggestion] World Generation

### ISSUE THREAD

**Issue by Dissgruntled** [coderbot16/SimpleFlax#6]
Since villagers grief the flax plants maybe instead of village generation you could do configurable world generation. I think it would make the worlds look just a little bit nicer spawning in and seeing these plants from time to time in world.

**Comment by coderbot16** [comment]
That sounds like a neat idea, but it could be a bit of work because I would need a separate worldgen flax plant to prevent normal flax plants from being farmable on normal dirt/grass. I was considering other solutions to the issue, and I'm currently looking at whether it would be possible to block villagers from harvesting the plants entirely.

**Comment by coderbot16** [comment]
I was able to fix #3 in https://github.com/coderbot16/SimpleFlax/commit/b7323abd2ef9e29bb85c772c2f0ae3ba00a88534, but I will leave this open as a suggestion for another time. The root issue is fixed, however. Thanks for the suggestion!

**Comment by coderbot16** [comment]
The latest update adds optional, disabled by default wild flax plants, configurable through the "flaxPerChunk" option. I recommend 8, which places flax rather sparsely but still visibly.
