### ISSUE TITLE
When the crop is fully grown (and harvestable), The One Probe only shows that the top is 80% grown, will never get higher.

### ISSUE THREAD

**Issue by ghost** [coderbot16/SimpleFlax#8]
I assume that this is a bug with SimpleFlax and not TheOneProbe because all other crops work fine. The bottom will say fully grown, but the top will say 80%

[Bottom](https://imgur.com/HXEuVTP)
[Top](https://imgur.com/XxsgPVV)

**Comment by coderbot16** [comment]
This is due to how SimpleFlax uses the AGE block property, and how TheOneProbe reads it. SimpleFlax plants have a real age value that ranges from 0-4 (MAX_AGE of 4), but the integer property ranges from 0-5. Rather than ask the plant what its MAX_AGE is, TheOneProbe instead just checks the maximum value of the integer property, meaning that it interprets the maximum as 5 instead of 4.

So, what is age 5 used for? Age 5 is a special value used for lower plants, that indicates that in addition to being a fully grown lower half, there is also a fully grown upper half on top. This is used for determining whether a plant should provide drops when broken.

To fix this, I just need to add an IBlockDisplayOverride for SimpleFlax crops, to override the default display with one that properly handles the age value.

**Comment by ghost** [comment]
That would be great if you could! i've watched multiple streams of my modpack players confused because the plant does not appear fully grown, so they believe they can't get string, so they think they are stuck in the progression.

**Comment by coderbot16** [comment]
Ah, that makes sense. Kinda ironic because TOP usually clarifies things, but in this case it only confuses players. I'll try to get a fix out in a few days, I'll ping you once it's ready.

**Comment by coderbot16** [comment]
Fix uploaded, should be available soon: https://minecraft.curseforge.com/projects/simpleflax/files/2720201
